root: true
env:
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:@typescript-eslint/strict'
  - 'airbnb-base'
  - 'airbnb-typescript/base'
plugins:
  - '@typescript-eslint'
rules:
  'no-void': 'off'
  'arrow-body-style': 'off'
  '@typescript-eslint/no-unused-vars': 'off'
  '@typescript-eslint/require-await': 'off'
